Update proxy method & some other listed updates.
chaos-mesh/rs-tproxy pull request #10
Opened 2021-07-11 22:10 UTC by Andrewmatilde

###Feature
1. [Done] Complete the proxy method of rs-tproxy, now rs-tproxy will be a real transparent proxy.
2. [Done] Now tcp package parsed with http parse error will be transfered into a tcp direct connection, which means user can use tcp broadcast mode on rs-tproxy without setting port and http packet with error injected by rs-tproxy will not be reject by itself.
3. [Done] Since network changes in Feature 1 ,rs-tproxy was splite into the main netns and a sub netns. Now the iptables rules is setting in the sub netns which may bring more safety on setting it and clear it. But not tproxy will take a default network device and its ip to a veth device
4. [WIP] Add http deamon config server mode for updating config. Now rs-tproxy has a stdio interactive mode with wraped http to send json packet config.

### Todo

- [ ]  feature 4(may delay)
- [ ]  group imports
- [ ]  complete todo in code
- [ ]  Manual test
- [ ]  Unit test
- [ ]  Stress test
- [ ]  E2E test
- [ ]  tech doc
- [ ]  review doc

2021-07-14 02:59 UTC, cwen0 commented on Cargo.toml
> +hyper = {git = "https://github.com/Andrewmatilde/hyper.git", features = ["runtime", "client", "server", "http1", "http2", "stream", "error_return"]}
why need a fork repo here?

2021-07-14 03:04 UTC, Andrewmatilde commented on Cargo.toml
> +hyper = {git = "https://github.com/Andrewmatilde/hyper.git", features = ["runtime", "client", "server", "http1", "http2", "stream", "error_return"]}
I have configured hyper , add a pub method called serve_connection_with_parts and add some customed implement.The method will return error instead of return 404 when it comes to a http parse error.

2021-07-14 04:52 UTC, Andrewmatilde commented on Cargo.toml
> +hyper = {git = "https://github.com/Andrewmatilde/hyper.git", features = ["runtime", "client", "server", "http1", "http2", "stream", "error_return"]}
Because of this , if user send https or ssh message to the port , proxy will meet a parse error and turn into tcp transfer.

2021-07-15 05:52 UTC, Andrewmatilde commented
Ping @Hexilee .

2021-07-22 14:09 UTC, Hexilee requested changes
Rest LGTM

2021-07-22 14:09 UTC, Hexilee commented on rs-tproxy-controller/src/proxy/uds_server.rs
> +                    loop {
The `UnixStream` of tokio implements [`AsyncWrite`](https://docs.rs/tokio/1.9.0/tokio/net/struct.UnixStream.html#impl-AsyncWrite), just use [`stream.write_all(&buf).await?`](https://docs.rs/tokio/1.9.0/tokio/io/trait.AsyncWriteExt.html#method.write_all) to write it.

2021-07-22 14:09 UTC, Hexilee commented on rs-tproxy-controller/src/proxy/uds_server.rs
> +                    loop {
Moreover, I think you should spawn the writing task as a new coroutine to avoid blocking of listening task.

2021-07-22 14:09 UTC, Hexilee commented on rs-tproxy-proxy/src/uds_client.rs
> +            stream.readable().await?;
The `UnixStream` also implements `AsyncRead`.

2021-07-22 14:09 UTC, Hexilee commented on rs-tproxy-proxy/src/proxy/http/connector.rs
> +        return Err(anyhow!("http connector cannot handle http request"));
```suggestion
        return Err(anyhow!("http connector cannot handle https request"));
```

2021-08-16 06:16 UTC, Andrewmatilde commented on rs-tproxy-controller/src/proxy/uds_server.rs
> +                    loop {
I do not use async api here because the listening task must be work after the writing task complete totally . 
So I think use serial  api here may be more clear and can avoid some mistake.

2021-08-16 06:18 UTC, Andrewmatilde commented on rs-tproxy-controller/src/proxy/uds_server.rs
> +                    loop {
And I remembered i have mocked some mistakes when using async api.

2021-08-16 06:18 UTC, Andrewmatilde commented on rs-tproxy-proxy/src/proxy/http/connector.rs
> +        return Err(anyhow!("http connector cannot handle http request"));
OK.

2021-08-16 06:20 UTC, Andrewmatilde commented on rs-tproxy-controller/src/cmd/interactive/handler.rs
> +                    Ok::<_, anyhow::Error>(())
We need to hint the error type of result here.

2021-08-16 06:21 UTC, Andrewmatilde commented on rs-tproxy-controller/src/proxy/config.rs
> +                    Some(b) => b.clone(),
thx

2021-08-16 06:23 UTC, Andrewmatilde commented on rs-tproxy-controller/src/proxy/exec.rs
> +        (&mut proxy)
The stdin method need proxy here to be mutable.

2021-08-16 06:24 UTC, Andrewmatilde commented on rs-tproxy-controller/src/proxy/exec.rs
> +        (&mut proxy)
In line 107.

2021-08-18 06:15 UTC, Andrewmatilde commented on rs-tproxy-controller/src/proxy/uds_server.rs
> +                    loop {
Sorry, you are right , I misunderstand it.I have fixed it.

2021-08-18 06:21 UTC, Andrewmatilde commented on rs-tproxy-controller/src/proxy/uds_server.rs
> +                    loop {
It makes me comfused that tokio use try_write in their comment.

2021-08-18 06:24 UTC, Andrewmatilde commented on rs-tproxy-controller/src/proxy/uds_server.rs
> +                    loop {
I have read their source code , and find write_all will not bring mistakes since wouldblock error have been handled by  
 code in AsyncWrite.

2021-08-18 06:27 UTC, Andrewmatilde commented on rs-tproxy-proxy/src/uds_client.rs
> +            stream.readable().await?;
fixed

2021-08-18 07:16 UTC, Hexilee commented on rs-tproxy-controller/src/proxy/exec.rs
> +        (&mut proxy)
Yes, but we do not need explicitly mutable referring. I think replacing `&mut proxy` with just `proxy` also works here.

2021-08-18 09:48 UTC, Andrewmatilde commented on rs-tproxy-controller/src/proxy/exec.rs
> +        (&mut proxy)
fixed

2021-08-19 07:54 UTC, Hexilee approved these changes
Rest LGTM

2021-08-19 07:54 UTC, Hexilee commented on rs-tproxy-controller/src/proxy/uds_server.rs
> +                                tracing::debug!(
Why not use `error` level logs here?

2021-08-19 07:54 UTC, Hexilee commented on rs-tproxy-controller/src/proxy/uds_server.rs
> +                    tracing::debug!("error : accept connection failed");
As line 41

2021-08-20 03:40 UTC, Andrewmatilde commented on rs-tproxy-controller/src/proxy/uds_server.rs
> +                                tracing::debug!(
fixed

2021-08-20 03:40 UTC, Andrewmatilde commented on rs-tproxy-controller/src/proxy/uds_server.rs
> +                    tracing::debug!("error : accept connection failed");
fixed

2021-08-23 11:35 UTC, Hexilee commented
Is this PR ready to merge now?@Andrewmatilde

2021-08-24 04:17 UTC, Hexilee commented
Why do we introduce actix?

2021-08-24 04:29 UTC, Andrewmatilde commented
> Why do we introduce actix? It's too heavy. @Andrewmatilde

I will delete it .

2021-08-24 04:37 UTC, Andrewmatilde commented on Cargo.lock
> +name = "miow"
ignore

2021-08-24 05:00 UTC, Andrewmatilde commented on Cargo.toml
> +rs-tproxy-proxy = {path = "./rs-tproxy-proxy"}
help

2021-08-24 05:05 UTC, Andrewmatilde commented on Cargo.toml
> +rs-tproxy-proxy = {path = "./rs-tproxy-proxy"}
ignore

2021-08-24 05:06 UTC, Andrewmatilde commented on Cargo.lock
>  name = "tokio"
ignore

2021-08-24 05:06 UTC, Andrewmatilde commented on Cargo.lock
>  name = "tokio"
ignore

2021-08-24 05:14 UTC, Andrewmatilde commented on Cargo.lock
>  name = "tokio"
ignore

2021-08-24 05:14 UTC, Andrewmatilde commented on Cargo.lock
>  name = "tokio"
ignore

2021-08-25 02:38 UTC, Hexilee commented on tests/exec.py
> +    test = subprocess.Popen("cargo test --release -- --ignored test_http_action::test_http_content_length_replace", shell=True)
Why do we ignore the `test_http_content_length_replace` test?

2021-08-25 03:41 UTC, Andrewmatilde commented on tests/exec.py
> +    test = subprocess.Popen("cargo test --release -- --ignored test_http_action::test_http_content_length_replace", shell=True)
Because test_http_content_length_replace rely on both the checker server in ./integration/checker.py and a release only feature in hyper.

2021-08-31 11:20 UTC, Andrewmatilde commented on Cargo.lock
>  name = "hyper"
ignore

2021-08-31 11:20 UTC, Andrewmatilde commented on Cargo.toml
> +rs-tproxy-proxy = {path = "./rs-tproxy-proxy"}
ignore

2021-08-31 16:40 UTC, Andrewmatilde commented
Here is a benchmark to show the base cost of rs-tproxy now.
**Steps:**

- Get a fast simple file server, I use [sfz](https://github.com/weihanglo/sfz) here.
- Generate a small target file(about 20 bytes).
 `dd if=/dev/zero of=20b-file bs=20 count=1 && xxd 20b-file > test.txt`
- Run sfz:
 `./sfz -b 0.0.0.0`
- Start rs-tproxy:
`sudo ./target/debug/rs-tproxy ./config-examples/one-line.json`
- Start proxy benchmark:
```
ab -n 10000 -c 100 http://172.19.0.8:5000/test.txt
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 172.19.0.8 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        sfz/0.6.1
Server Hostname:        172.19.0.8
Server Port:            5000

Document Path:          /test.txt
Document Length:        124 bytes

Concurrency Level:      100
Time taken for tests:   9.634 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      3870000 bytes
HTML transferred:       1240000 bytes
Requests per second:    1038.02 [#/sec] (mean)
Time per request:       96.337 [ms] (mean)
Time per request:       0.963 [ms] (mean, across all concurrent requests)
Transfer rate:          392.30 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       2
Processing:     3   96  18.6     92     216
Waiting:        1   96  18.5     92     216
Total:          4   96  18.6     92     216

Percentage of the requests served within a certain time (ms)
  50%     92
  66%     96
  75%    100
  80%    102
  90%    107
  95%    113
  98%    176
  99%    184
 100%    216 (longest request)
```
- Close rs-tproxy & retry:
``` 
ab -n 10000 -c 100 http://172.19.0.8:5000/test.txt
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 172.19.0.8 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        sfz/0.6.1
Server Hostname:        172.19.0.8
Server Port:            5000

Document Path:          /test.txt
Document Length:        124 bytes

Concurrency Level:      100
Time taken for tests:   1.126 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      3870000 bytes
HTML transferred:       1240000 bytes
Requests per second:    8883.35 [#/sec] (mean)
Time per request:       11.257 [ms] (mean)
Time per request:       0.113 [ms] (mean, across all concurrent requests)
Transfer rate:          3357.28 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       2
Processing:     1   11   2.7     10      19
Waiting:        0   11   2.7     10      19
Total:          3   11   2.7     10      19

Percentage of the requests served within a certain time (ms)
  50%     10
  66%     11
  75%     13
  80%     14
  90%     15
  95%     16
  98%     17
  99%     17
 100%     19 (longest request)
``` 

Now we get a simple view of base cost of rs-tproxy.
I test this on 1c2g vm. Rs-tproxy may be faster on your computer.

2021-09-02 05:32 UTC, Hexilee approved these changes
LGTM

2021-09-02 05:32 UTC, merged

2021-09-02 06:00 UTC, Andrewmatilde commented
ADD: benchmark of release version
```
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 172.19.0.8 (be patient)
Completed 200 requests
Completed 400 requests
Completed 600 requests
Completed 800 requests
Completed 1000 requests
Completed 1200 requests
Completed 1400 requests
Completed 1600 requests
Completed 1800 requests
Completed 2000 requests
Finished 2000 requests


Server Software:        sfz/0.6.1
Server Hostname:        172.19.0.8
Server Port:            5000

Document Path:          /test.txt
Document Length:        124 bytes

Concurrency Level:      100
Time taken for tests:   0.458 seconds
Complete requests:      2000
Failed requests:        0
Total transferred:      774000 bytes
HTML transferred:       248000 bytes
Requests per second:    4365.59 [#/sec] (mean)
Time per request:       22.906 [ms] (mean)
Time per request:       0.229 [ms] (mean, across all concurrent requests)
Transfer rate:          1649.89 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   1.0      0       6
Processing:     3   22   3.0     22      30
Waiting:        1   22   3.0     22      30
Total:          5   22   2.5     23      30

Percentage of the requests served within a certain time (ms)
  50%     23
  66%     23
  75%     24
  80%     24
  90%     25
  95%     26
  98%     27
  99%     28
 100%     30 (longest request)```